const LABELS: Record<string, string> = {
  "sale.created": "Sale created",
  "sale.published": "Sale published",
  "sale.unpublished": "Sale reverted to draft",
  "sale.cancelled": "Sale cancelled",
  "sale.soft_deleted": "Sale deleted",
  "lot.soft_deleted": "Lot deleted",
  "sale.ended": "Sale marked ended",
  "lot.created": "Lot created",
  "lot.activated": "Lot went live",
  "lot.attached_to_sale": "Attached to sale",
  "lot.detached_from_sale": "Detached from sale",
  "lot.published": "Lot scheduled",
  "lot.unpublished": "Lot reverted to draft",
  "lot.cancelled": "Lot cancelled",
  "lot.ended": "Lot ended",
  "lot.voided": "Lot voided",
  "lot.withdrawal_requested": "Withdrawal requested",
  "lot.returned_to_inventory": "Returned to inventory",
  "bid.placed": "Bid placed",
  "bid.proxy_cancelled": "Proxy bid cancelled",
  "condition_report.requested": "Condition report requested",
  "condition_report.fulfilled": "Condition report fulfilled",
  "condition_report.declined": "Condition report declined",
  "category.created": "Category created",
  "category.updated": "Category updated",
  "category.archived": "Category archived",
  "category.deleted": "Category deleted",
  "artist.deleted": "Artist deleted",
  "payment.dispute_opened": "Dispute opened",
  "payment.dispute_funds_withdrawn": "Dispute funds withdrawn",
  "payment.dispute_closed": "Dispute closed",
  "payment.created": "Payment created",
  "payment.authorized": "Payment authorized",
  "payment.captured": "Payment captured",
  "payment.refunded": "Payment refunded",
  "payment.cancelled": "Payment cancelled",
  "payment.manual_review_required": "Manual review required",
  "payout.scheduled": "Payout scheduled",
  "payout.paid": "Payout paid",
  "payout.failed": "Payout failed",
  "payout.reversed": "Payout reversed",
  "legal_entity.created": "Legal entity created",
  "legal_entity.updated": "Legal entity updated",
  "legal_entity.stripe_connect_linked": "Stripe Connect linked",
  "legal_entity.stripe_connect_requirements_updated": "Stripe requirements updated",
  "venue.created": "Venue created",
  "venue.updated": "Venue updated",
  "venue.archived": "Venue archived",
  "aml.screening_completed": "AML screening completed",
  "aml.screening_cleared": "AML screening cleared",
  "aml.screening_blocked": "AML screening blocked",
  "source_of_funds.case_opened": "Source of Funds case opened",
  "source_of_funds.approved": "Source of Funds approved",
  "source_of_funds.rejected": "Source of Funds rejected",
  "source_of_funds.document_reviewed": "Source of Funds document reviewed",
  "kyc.session_started": "KYC session started",
  "kyc.session_completed": "KYC session completed",
  "auth.user_suspended": "User suspended",
  "auth.user_reactivated": "User reactivated",
  "admin.impersonation_started": "Impersonation started",
  "admin.impersonation_ended": "Impersonation ended",
  "item_submission.submitted": "Submission received",
  "item_submission.approved": "Submission approved",
  "item_submission.rejected": "Submission rejected",
};

export function domainEventLabel(eventType: string): string {
  if (LABELS[eventType]) return LABELS[eventType];
  const parts = eventType.split(".");
  const verb = parts[parts.length - 1] ?? eventType;
  return verb.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
