export const SHOP_API_ERROR_CODES = {
  VALIDATION: "shop.validation",
  NOT_FOUND: "shop.not_found",
  CONFLICT: "shop.conflict",
  INTERNAL: "shop.internal",
  OUT_OF_STOCK: "shop.out_of_stock",
  BASKET_CONFLICT: "shop.basket_conflict",
  PRICE_CHANGED: "shop.price_changed",
  PAYMENT_FAILED: "shop.payment_failed",
  UNAUTHORIZED: "shop.unauthorized",
  FORBIDDEN: "shop.forbidden",
  STAFF_REQUIRED: "shop.staff_required",
  STEP_UP_REQUIRED: "shop.step_up_required",
  POLICY_NOT_CONFIGURED: "shop.policy_not_configured",
  AUTHORITY_INSUFFICIENT: "shop.authority_insufficient",
  EDITION_NOT_SELLABLE: "shop.edition_not_sellable",
  HOLD_CONFLICT: "shop.hold_conflict",
  PAYOUT_BLOCKED: "shop.payout_blocked",
  REFUND_FAILED: "shop.refund_failed",
  STAFF_FORBIDDEN: "shop.staff_forbidden",
  FEATURE_DISABLED: "shop.feature_disabled",
  IDEMPOTENCY_CONFLICT: "shop.idempotency_conflict",
} as const;

export type ShopApiErrorCode = (typeof SHOP_API_ERROR_CODES)[keyof typeof SHOP_API_ERROR_CODES];
