import type { SaleHeroVM } from "@/components/sections/saleroom/view-models";

export const saleroomHeroFixture: SaleHeroVM = {
  id: "sale-1",
  title: "Modern British Art",
  coverImage: "https://example.com/cover.jpg",
  startEndLabel: "12–14 June 2026",
  status: "active",
  startTime: "2026-06-12T12:00:00.000Z",
  endTime: "2026-06-14T18:00:00.000Z",
  isLive: true,
  registrationClosesLabel: null,
  biddingStartsLabel: null,
  description: null,
  shareUrl: "https://example.com/sales/modern-british-art/sale-1",
  itemsLabel: "120 lots",
  tags: [],
  dateLine: "12–14 June 2026",
  registrationClosesShort: null,
  biddingStartsShort: null,
  leftColumnLabel: null,
  rightColumnLabel: "Bidding",
  overviewMetaLine: "Online only",
  liveLotsCount: 8,
};
