# Google Tag Manager server-side tagging (SST) cluster.
# https://developers.google.com/tag-platform/tag-manager/server-side/manual-setup-guide
# Pinned 2026-05-18 (was :stable). Re-pin with: docker buildx imagetools inspect gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
FROM gcr.io/cloud-tagging-10302018/gtm-cloud-image@sha256:f04589802ffb44bcff0a367c749ce939c17af895888aef2278adda709def3e88
EXPOSE 8080
