export const venueStatuses = ["active", "archived"] as const;
export type VenueStatus = (typeof venueStatuses)[number];

export type Venue = {
  id: string;
  legalEntityId: string;
  name: string;
  slug: string | null;
  addressLine1: string;
  addressLine2: string | null;
  city: string;
  county: string | null;
  postcode: string;
  country: string;
  mapUrl: string | null;
  latitude: number | null;
  longitude: number | null;
  openingHours: Record<string, unknown> | null;
  contactPhone: string | null;
  contactEmail: string | null;
  website: string | null;
  photos: string[];
  capacity: number | null;
  accessNotes: string | null;
  parkingNotes: string | null;
  directionsNotes: string | null;
  status: VenueStatus;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
  deletedByUserId?: string | null;
};

export type CreateVenueInput = {
  legalEntityId: string;
  name: string;
  addressLine1: string;
  addressLine2?: string | null | undefined;
  city: string;
  county?: string | null | undefined;
  postcode: string;
  country: string;
  mapUrl?: string | null | undefined;
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  openingHours?: Record<string, unknown> | null | undefined;
  contactPhone?: string | null | undefined;
  contactEmail?: string | null | undefined;
  website?: string | null | undefined;
  photos?: string[] | undefined;
  capacity?: number | null | undefined;
  accessNotes?: string | null | undefined;
  parkingNotes?: string | null | undefined;
  directionsNotes?: string | null | undefined;
};

export type UpdateVenueInput = {
  legalEntityId?: string | undefined;
  name?: string | undefined;
  addressLine1?: string | undefined;
  addressLine2?: string | null | undefined;
  city?: string | undefined;
  county?: string | null | undefined;
  postcode?: string | undefined;
  country?: string | undefined;
  mapUrl?: string | null | undefined;
  latitude?: number | null | undefined;
  longitude?: number | null | undefined;
  openingHours?: Record<string, unknown> | null | undefined;
  contactPhone?: string | null | undefined;
  contactEmail?: string | null | undefined;
  website?: string | null | undefined;
  photos?: string[] | undefined;
  capacity?: number | null | undefined;
  accessNotes?: string | null | undefined;
  parkingNotes?: string | null | undefined;
  directionsNotes?: string | null | undefined;
  status?: VenueStatus | undefined;
};
