CREATE TABLE IF NOT EXISTS "bid_user_profile" (
  "user_id" text PRIMARY KEY NOT NULL REFERENCES "user"("id") ON DELETE cascade,
  "role" text DEFAULT 'client' NOT NULL,
  "staff_role" "user_staff_role",
  "email_status" text DEFAULT 'ok' NOT NULL,
  "email_status_changed_at" timestamp with time zone,
  "suspended_at" timestamp with time zone,
  "suspended_reason" text,
  "kyc_status" "user_kyc_status" DEFAULT 'unverified' NOT NULL,
  "current_kyc_session_id" text,
  "kyc_retry_count" integer DEFAULT 0 NOT NULL,
  "kyc_verified_at" timestamp with time zone,
  "preferred_paddle_number" integer,
  "aml_hold_status" "user_aml_hold_status" DEFAULT 'none' NOT NULL,
  "aml_hold_reason" text,
  "aml_hold_at" timestamp with time zone,
  "signup_persona" text,
  "date_of_birth" date,
  "first_name" text,
  "last_name" text,
  "mobile" text,
  "mobile_country" text,
  "has_seen_acting_context_tooltip" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shop_user_profile" (
  "identity_subject_id" text PRIMARY KEY NOT NULL,
  "email" text,
  "name" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
INSERT INTO "bid_user_profile" (
  "user_id",
  "role",
  "staff_role",
  "email_status",
  "email_status_changed_at",
  "suspended_at",
  "suspended_reason",
  "kyc_status",
  "current_kyc_session_id",
  "kyc_retry_count",
  "kyc_verified_at",
  "preferred_paddle_number",
  "aml_hold_status",
  "aml_hold_reason",
  "aml_hold_at",
  "signup_persona",
  "date_of_birth",
  "first_name",
  "last_name",
  "mobile",
  "mobile_country",
  "has_seen_acting_context_tooltip",
  "created_at",
  "updated_at"
)
SELECT
  u."id",
  u."role",
  u."staff_role",
  u."email_status",
  u."email_status_changed_at",
  u."suspended_at",
  u."suspended_reason",
  u."kyc_status",
  u."current_kyc_session_id",
  u."kyc_retry_count",
  u."kyc_verified_at",
  u."preferred_paddle_number",
  u."aml_hold_status",
  u."aml_hold_reason",
  u."aml_hold_at",
  u."signup_persona",
  u."date_of_birth",
  u."first_name",
  u."last_name",
  u."mobile",
  u."mobile_country",
  u."has_seen_acting_context_tooltip",
  u."created_at",
  u."updated_at"
FROM "user" u
ON CONFLICT ("user_id") DO NOTHING;
