import { createDb } from "@auction/db";
import type { Container, ContainerComposedSlices } from "./container/container-slices.js";
import { createAdminServices } from "./container/create-admin-services.js";
import { createContainerAuthenticator } from "./container/create-auth.js";
import { createBiddingRouteServices } from "./container/create-bidding-route-services.js";
import { createBiddingSaleroom } from "./container/create-bidding-saleroom.js";
import { createCatalogRouteServices } from "./container/create-catalog-route-services.js";
import { createCatalogServices } from "./container/create-catalog-services.js";
import { createComplianceMedia } from "./container/create-compliance-media.js";
import { createComplianceRouteServices } from "./container/create-compliance-route-services.js";
import { createCronServices } from "./container/create-cron-services.js";
import { createFinanceRouteServices } from "./container/create-finance-route-services.js";
import { createIdentityRouteServices } from "./container/create-identity-route-services.js";
import { createInfra } from "./container/create-infra.js";
import { createLotLifecycle } from "./container/create-lot-lifecycle.js";
import { createPaymentsServices } from "./container/create-payments-services.js";
import { createPlatformCronRouteServices } from "./container/create-platform-cron-route-services.js";
import { createPlatformServices } from "./container/create-platform-services.js";
import { createRepositories } from "./container/create-repositories.js";
import { createSubmissionRouteServices } from "./container/create-submission-route-services.js";
import { createUserMiscServices } from "./container/create-user-misc-services.js";
import { createUserNotificationComposition } from "./container/create-user-notification-composition.js";
import { createUserRouteServices } from "./container/create-user-route-services.js";
import type { Env } from "./env.js";
import { DrizzleSubjectUsageReader } from "./infrastructure/drizzle-subject-usage.reader.js";
import { HttpIdentityIssuerClient } from "./infrastructure/http-identity-issuer.client.js";
import { RedisOAuthAttributionStore } from "./infrastructure/redis-oauth-attribution.store.js";
import { EnsurePersonalLegalEntityService } from "./services/legal-entity/ensure-personal-legal-entity.service.js";
import { SessionRevocationService } from "./services/session-revocation.service.js";

export type { Container, ContainerComposedSlices };

export function createContainer(env: Env): Container {
  const db = createDb(env.DATABASE_URL_API ?? env.DATABASE_URL);
  const infra = createInfra(env, db);
  const oauthAttributionStore = new RedisOAuthAttributionStore(infra.redis);
  const identityIssuer = new HttpIdentityIssuerClient({
    issuerBaseUrl: env.OIDC_INTERNAL_BASE_URL ?? env.OIDC_ISSUER_URL,
    defaultOrigin: env.WEB_ORIGIN,
    ...(env.IDENTITY_MACHINE_CLIENT_ID ? { machineClientId: env.IDENTITY_MACHINE_CLIENT_ID } : {}),
    ...(env.IDENTITY_MACHINE_CLIENT_SECRET
      ? { machineClientSecret: env.IDENTITY_MACHINE_CLIENT_SECRET }
      : {}),
  });
  const sessionRevocation = new SessionRevocationService(identityIssuer);
  const subjectUsageReader = new DrizzleSubjectUsageReader(db);
  const ensurePersonalLegalEntityService = new EnsurePersonalLegalEntityService(db);
  const authenticator = createContainerAuthenticator({ env, db });

  const repos = createRepositories(db, identityIssuer);

  const userNotification = createUserNotificationComposition(repos);

  const platform = createPlatformServices({ env, db, infra, repos });
  const lotLifecycle = createLotLifecycle({ infra, repos, platform });
  const complianceMedia = createComplianceMedia({ env, db, infra, repos, platform });
  const catalog = createCatalogServices({
    env,
    db,
    infra,
    repos,
    platform,
    lotLifecycle,
    complianceMedia,
  });
  const payments = createPaymentsServices({
    env,
    db,
    infra,
    repos,
    platform,
    complianceMedia,
    catalog,
  });
  const biddingSaleroom = createBiddingSaleroom({
    env,
    db,
    infra,
    repos,
    platform,
    lotLifecycle,
    complianceMedia,
    catalog,
    adminMetricsService: payments.adminMetricsService,
  });
  const userMisc = createUserMiscServices({
    env,
    db,
    identityIssuer,
    ensurePersonalLegalEntityService,
    infra,
    repos,
    platform,
    complianceMedia,
    catalog,
    payments,
  });
  const cron = createCronServices({
    env,
    db,
    infra,
    repos,
    platform,
    payments,
    catalog,
    lotLifecycle,
    biddingSaleroom,
    complianceMedia,
  });
  const compliance = createComplianceRouteServices({
    db,
    transactionRunner: platform.transactionRunner,
    legalEntityRepository: repos.legalEntityRepository,
    domainEventSink: platform.domainEventSink,
    kycService: complianceMedia.kycService,
    amlService: complianceMedia.amlService,
    stripeConnectService: platform.stripeConnectService,
    marketingEventService: complianceMedia.marketingEventService,
    kycResubmissionNotifier: complianceMedia.kycResubmissionNotifier,
    sourceOfFundsDocumentCollectionService: complianceMedia.sourceOfFundsDocumentCollectionService,
    uploadService: complianceMedia.uploadService,
    exportService: complianceMedia.exportService,
    lotDocumentService: complianceMedia.lotDocumentService,
    saleDocumentService: complianceMedia.saleDocumentService,
    storageDriver: env.STORAGE_DRIVER,
  });
  const finance = createFinanceRouteServices({
    redis: infra.redis,
    legalEntityRepository: repos.legalEntityRepository,
    payoutRepository: repos.payoutRepository,
    payoutStatementQueue: infra.payoutStatementQueue,
    paymentAdminService: payments.paymentAdminService,
    paymentBuyerService: payments.paymentBuyerService,
    buyerComplianceHttp: compliance.buyerComplianceHttp,
    lotFulfilmentBuyerService: payments.lotFulfilmentService,
    marketingEventService: complianceMedia.marketingEventService,
    attributionStore: complianceMedia.attributionStore,
    marketingAttributionEnabled: complianceMedia.marketingAttributionEnabled,
    sourceOfFundsDocumentCollectionService: complianceMedia.sourceOfFundsDocumentCollectionService,
    settlementCronService: cron.settlementCronService,
    paymentMaintenanceCronService: cron.paymentMaintenanceCronService,
    accountingReplayCronService: cron.accountingReplayCronService,
    stripeWebhookVerifier: infra.stripeWebhookVerifier,
    stripeConnectService: platform.stripeConnectService,
    stripePaymentWebhookService: payments.stripePaymentWebhookService,
    payoutSellerService: platform.payoutSellerService,
    env,
    xeroWebhookEventRepository: repos.xeroWebhookEventRepository,
    accountingProvider: payments.accountingProvider,
    webhookEventRepository: repos.webhookEventRepository,
    webhookEventsProducer: infra.webhookEventsProducer,
  });
  const platformCron = createPlatformCronRouteServices({
    redis: infra.redis,
    lifecycleCronService: cron.lifecycleCronService,
    hygieneCronService: cron.hygieneCronService,
  });
  const catalogRoutes = createCatalogRouteServices({
    saleService: catalog.saleService,
    saleSoftDeleteService: catalog.saleSoftDeleteService,
    saleStatusTransitionService: catalog.saleStatusTransitionService,
    lotService: catalog.lotService,
    lotSoftDeleteService: catalog.lotSoftDeleteService,
    mediaUrlResolver: complianceMedia.mediaUrlResolver,
    mediaAssetEnricher: complianceMedia.mediaAssetEnricher,
    db,
    objectStorage: infra.objectStorage,
    cachedCatalogueListService: platform.cachedCatalogueListService,
    lotLifecycleQueryService: catalog.lotLifecycleQueryService,
    stripeConnectService: platform.stripeConnectService,
    legalEntityRepository: repos.legalEntityRepository,
    saleListReadService: catalog.saleListReadService,
    repoFactory: repos.repoFactory,
    saleroomService: biddingSaleroom.saleroomService,
    saleBiddersService: catalog.saleBiddersService,
    categoryService: catalog.categoryService,
    pressArchiveReadService: catalog.pressArchiveReadService,
    saleFollowService: catalog.saleFollowService,
    artistRegistryService: platform.artistRegistryService,
    artistProfileService: catalog.artistProfileService,
    artistDeleteService: catalog.artistDeleteService,
    venueService: catalog.venueService,
  });
  const submissionRoutes = createSubmissionRouteServices({
    itemSubmissionSellerApi: catalog.itemSubmissionSellerApi,
    itemSubmissionAdminApi: catalog.itemSubmissionAdminApi,
    submissionDocumentService: complianceMedia.submissionDocumentService,
  });
  const admin = createAdminServices({
    env,
    db,
    infra,
    repos,
    platform,
    complianceMedia,
    catalog,
    payments,
    bidding: biddingSaleroom,
    userMisc,
    payoutStatementApplication: finance.payoutStatement,
  });

  return {
    env,
    db,
    sessionRevocation,
    redis: infra.redis,
    rateLimitStore: infra.rateLimitStore,
    vapidPublicKey: env.VAPID_PUBLIC_KEY ?? null,
    authenticator,
    identityIssuer,
    subjectUsageReader,
    oauthAttributionStore,
    authOAuthAccountReader: identityIssuer,
    repoFactory: repos.repoFactory,
    lotService: catalog.lotService,
    conditionReportService: catalog.conditionReportService,
    saleService: catalog.saleService,
    saleListReadService: catalog.saleListReadService,
    pressArchiveReadService: catalog.pressArchiveReadService,
    saleSoftDeleteService: catalog.saleSoftDeleteService,
    lotSoftDeleteService: catalog.lotSoftDeleteService,
    saleFollowService: catalog.saleFollowService,
    saleBiddersService: catalog.saleBiddersService,
    saleRegistrationService: biddingSaleroom.saleRegistrationService,
    lotLifecycleService: lotLifecycle.lotLifecycleService,
    lotLifecycleQueryService: catalog.lotLifecycleQueryService,
    lotTransitionOrchestrator: catalog.lotTransitionOrchestrator,
    adminLotBrowseService: catalog.adminLotBrowseService,
    absenteeBidService: biddingSaleroom.absenteeBidService,
    telephoneBidBookingService: catalog.telephoneBidBookingService,
    paddleService: catalog.paddleService,
    saleroomCheckInService: catalog.saleroomCheckInService,
    onsiteEventPublicRsvpService: catalog.onsiteEventPublicRsvpService,
    onsiteEventAdminService: catalog.onsiteEventAdminService,
    onsiteEventPassService: catalog.onsiteEventPassService,
    onsiteEventStaffCheckInService: catalog.onsiteEventStaffCheckInService,
    adminSaleOperationsSnapshotService: biddingSaleroom.adminSaleOperationsSnapshotService,
    saleroomService: biddingSaleroom.saleroomService,
    displayPairingService: biddingSaleroom.displayPairingService,
    displayOverlayService: biddingSaleroom.displayOverlayService,
    displaySnapshotReader: biddingSaleroom.displaySnapshotReader,
    saleroomOnBlockPolicy: biddingSaleroom.saleroomOnBlockPolicy,
    lotFulfilmentService: payments.lotFulfilmentService,
    saleLifecycleService: lotLifecycle.saleLifecycleService,
    lotJobScheduler: catalog.lotJobScheduler,
    saleStatusTransitionService: catalog.saleStatusTransitionService,
    bidService: biddingSaleroom.bidService,
    autoBidService: biddingSaleroom.autoBidService,
    categoryService: catalog.categoryService,
    venueService: catalog.venueService,
    resolvePlatformCatalogLegalEntityId: catalog.resolvePlatformCatalogLegalEntityId,
    artistProfileService: catalog.artistProfileService,
    artistDeleteService: catalog.artistDeleteService,
    dashboardQueryService: catalog.dashboardQueryService,
    userDashboardReadService: userMisc.userDashboardReadService,
    cachedCatalogueListService: platform.cachedCatalogueListService,
    notificationQueryService: userNotification.notificationQueryService,
    lotInvoiceInitiationService: payments.lotInvoiceInitiationService,
    qrCodeService: catalog.qrCodeService,
    qrCodeAnalytics: catalog.qrCodeAnalytics,
    paymentRefundReconcileService: platform.paymentRefundReconcileService,
    accountingProvider: payments.accountingProvider,
    invoiceAddressingService: platform.invoiceAddressingService,
    xeroPayoutBillWriter: payments.xeroPayoutBillWriter,
    xeroPaymentRecorder: payments.xeroPaymentRecorder,
    xeroOAuthService: payments.xeroOAuthService,
    xeroWebhookEventRepository: repos.xeroWebhookEventRepository,
    userService: userMisc.userService,
    watchlistService: userMisc.watchlistService,
    savedSearchService: userMisc.savedSearchService,
    userSecurityReadService: userMisc.userSecurityReadService,
    newsletterSignupService: userMisc.newsletterSignupService,
    webhookEventRepository: repos.webhookEventRepository,
    artistWatchlistService: userMisc.artistWatchlistService,
    notificationService: platform.notificationService,
    notificationPreferenceRepository: repos.notificationPreferenceRepository,
    uiPreferenceRepository: repos.uiPreferenceRepository,
    uiPreferenceService: platform.uiPreferenceService,
    pushSubscriptionRepository: repos.pushSubscriptionRepository,
    notificationDispatcher: platform.notificationDispatcher,
    notificationOutboxProcessor: platform.notificationOutboxProcessor,
    notificationFactory: platform.notificationFactory,
    emailService: infra.emailService,
    emailObservabilityRepository: repos.emailObservabilityRepository,
    userSuspensionChecker: platform.cachedUserSuspensionChecker,
    userSuspensionCacheInvalidator: platform.cachedUserSuspensionChecker,
    registrationService: userMisc.registrationService,
    invitationService: userMisc.invitationService,
    invitationRepository: userMisc.invitationRepository,
    profileService: userMisc.profileService,
    addressService: userMisc.addressService,
    domainEventSink: platform.domainEventSink,
    transactionRunner: platform.transactionRunner,
    authAuditPublisher: platform.authAuditPublisher,
    legalEntityLifecycleAdminService: platform.legalEntityLifecycleAdminService,
    legalEntityDocumentAdminService: complianceMedia.legalEntityDocumentAdminService,
    impersonationAuditService: platform.impersonationAuditService,
    impersonationSessionService: platform.impersonationSessionService,
    legalEntityAccessService: platform.legalEntityAccessService,
    requireLegalEntityContext: platform.requireLegalEntityContext,
    requireSubmissionsLegalEntityContext: userMisc.requireSubmissionsLegalEntityContext,
    adminUserService: userMisc.adminUserService,
    adminPaymentListQueryService: userMisc.adminPaymentListQueryService,
    adminMetricsService: payments.adminMetricsService,
    attentionFeedReader: repos.attentionFeedReader,
    httpErrorHandler: userMisc.httpErrorHandler,
    itemSubmissionRepository: repos.itemSubmissionRepository,
    itemSubmissionService: catalog.itemSubmissionService,
    itemSubmissionSellerApi: catalog.itemSubmissionSellerApi,
    itemSubmissionAdminApi: catalog.itemSubmissionAdminApi,
    legalEntityRepository: repos.legalEntityRepository,
    personalLegalEntityResolver: userMisc.personalLegalEntityResolver,
    legalEntityNotificationRecipients: repos.legalEntityNotificationRecipients,
    kycRepository: repos.kycRepository,
    kycService: complianceMedia.kycService,
    kycResubmissionNotifier: complianceMedia.kycResubmissionNotifier,
    amlService: complianceMedia.amlService,
    sourceOfFundsService: complianceMedia.sourceOfFundsService,
    adminSourceOfFundsQueryService: complianceMedia.adminSourceOfFundsQueryService,
    sourceOfFundsDocumentCollectionService: complianceMedia.sourceOfFundsDocumentCollectionService,
    sourceOfFundsDocumentReviewService: complianceMedia.sourceOfFundsDocumentReviewService,
    organizationOnboardingService: platform.organizationOnboardingService,
    orgModuleGate: userMisc.orgModuleGate,
    organizationOnboardingFlowService: platform.organizationOnboardingFlowService,
    artistRegistryService: platform.artistRegistryService,
    stripeConnectService: platform.stripeConnectService,
    memberManagementService: platform.memberManagementService,
    pendingInvitationsReader: repos.pendingInvitationsReader,
    invitationLifecycleService: platform.invitationLifecycleService,
    transactionalMailer: platform.transactionalMailer,
    payoutRepository: repos.payoutRepository,
    payoutService: platform.payoutService,
    payoutSellerService: platform.payoutSellerService,
    payoutAdminService: platform.payoutAdminService,
    payoutSettlementService: platform.payoutSettlementService,
    payoutMaintenanceService: platform.payoutMaintenanceService,
    objectStorage: infra.objectStorage,
    mediaUrlResolver: complianceMedia.mediaUrlResolver,
    mediaAssetEnricher: complianceMedia.mediaAssetEnricher,
    uploadService: complianceMedia.uploadService,
    lotDocumentService: complianceMedia.lotDocumentService,
    saleDocumentService: complianceMedia.saleDocumentService,
    submissionDocumentService: complianceMedia.submissionDocumentService,
    uploadValidationQueue: infra.uploadValidationQueue,
    imageCleanupQueue: infra.imageCleanupQueue,
    marketingSyncQueue: infra.marketingSyncQueue,
    payoutStatementQueue: infra.payoutStatementQueue,
    dataExportQueue: infra.dataExportQueue,
    exportService: complianceMedia.exportService,
    legalEntityArchiveQueue: infra.legalEntityArchiveQueue,
    stripeClientFactory: infra.stripeClientFactory,
    stripeWebhookVerifier: infra.stripeWebhookVerifier,
    marketingEventService: complianceMedia.marketingEventService,
    marketingEventPublisher: complianceMedia.marketingEventPublisher,
    clickIdStore: complianceMedia.clickIdStore,
    attributionStore: complianceMedia.attributionStore,
    marketingAttributionEnabled: complianceMedia.marketingAttributionEnabled,
    postmarkWebhookService: userMisc.postmarkWebhookService,
    brevoWebhookIngestService: cron.brevoWebhookIngestService,
    accountDeletionEligibilityService: cron.accountDeletionEligibilityService,
    adminMarketingEventsService: userMisc.adminMarketingEventsService,
    emailUnsubscribeService: userMisc.emailUnsubscribeService,
    bidding: createBiddingRouteServices({
      bidPlacer: biddingSaleroom.bidService,
      absenteeBidService: biddingSaleroom.absenteeBidService,
      autoBidService: biddingSaleroom.autoBidService,
      conditionReportService: catalog.conditionReportService,
      saleRegistrationBuyer: biddingSaleroom.saleRegistrationService,
      telephoneBidBookingBuyer: catalog.telephoneBidBookingService,
      lotService: catalog.lotService,
      displayPairingService: biddingSaleroom.displayPairingService,
      displaySnapshotReader: biddingSaleroom.displaySnapshotReader,
    }),
    identityRoutes: createIdentityRouteServices({
      accountSecurity: {
        env,
        identityIssuer,
        userService: userMisc.userService,
        emailService: infra.emailService,
        authAuditPublisher: platform.authAuditPublisher,
        authCredentialReader: identityIssuer,
      },
      legalEntityRepository: repos.legalEntityRepository,
      personalLegalEntityResolver: userMisc.personalLegalEntityResolver,
      orgModuleGate: userMisc.orgModuleGate,
      userService: userMisc.userService,
      pendingInvitationsReader: repos.pendingInvitationsReader,
      invitationLifecycleService: platform.invitationLifecycleService,
      legalEntityAccessService: platform.legalEntityAccessService,
      memberManagementService: platform.memberManagementService,
      organizationOnboardingService: platform.organizationOnboardingService,
      organizationOnboardingFlowService: platform.organizationOnboardingFlowService,
    }),
    userRoutes: createUserRouteServices({
      env,
      registrationService: userMisc.registrationService,
      marketingEventService: complianceMedia.marketingEventService,
      attributionStore: complianceMedia.attributionStore,
      marketingAttributionEnabled: complianceMedia.marketingAttributionEnabled,
      userService: userMisc.userService,
      mediaUrlResolver: complianceMedia.mediaUrlResolver,
      conditionReportService: catalog.conditionReportService,
      userDashboardReadService: userMisc.userDashboardReadService,
      lotService: catalog.lotService,
      paymentBuyerService: payments.paymentBuyerService,
      mediaAssetEnricher: complianceMedia.mediaAssetEnricher,
      saleService: catalog.saleService,
      watchlistService: userMisc.watchlistService,
      artistWatchlistService: userMisc.artistWatchlistService,
      savedSearchService: userMisc.savedSearchService,
      notificationQueryService: userNotification.notificationQueryService,
      vapidPublicKey: env.VAPID_PUBLIC_KEY ?? null,
      pushSubscriptionRepository: repos.pushSubscriptionRepository,
      notificationPreferenceRepository: repos.notificationPreferenceRepository,
      uiPreferenceService: platform.uiPreferenceService,
      profileService: userMisc.profileService,
      addressService: userMisc.addressService,
      sessionRevocation,
      authAuditPublisher: platform.authAuditPublisher,
      userSecurityReadService: userMisc.userSecurityReadService,
      emailService: infra.emailService,
      accountDeletionEligibilityService: cron.accountDeletionEligibilityService,
    }),
    admin: admin.admin,
    finance,
    platformCron,
    compliance,
    catalogRoutes,
    submissionRoutes,
    queueAdmin: userMisc.queueAdmin,
    closeBullQueues: userMisc.closeBullQueues,
  };
}

export type {
  ContainerAdminMarketingEventsRoutesSlice,
  ContainerAdminOnsiteEventRoutesSlice,
  ContainerAdminPayoutRoutesSlice,
  ContainerAdminPlatformRoutesSlice,
  ContainerAdminQueuesRoutesSlice,
  ContainerAdminRoutesSlice,
  ContainerAdminSlice,
  ContainerArtistRoutesSlice,
  ContainerAuthRoutesSlice,
  ContainerBidRoutesSlice,
  ContainerBiddingRoutesSlice,
  ContainerIdentityRoutesSlice,
  ContainerBiddingSaleroomSlice,
  ContainerBrevoWebhookRoutesSlice,
  ContainerCatalogAdminReadersSlice,
  ContainerCatalogSlice,
  ContainerCategoryRoutesSlice,
  ContainerComplianceMediaSlice,
  ContainerCredentialSetupSlice,
  ContainerCronSlice,
  ContainerEmailRoutesSlice,
  ContainerExportRoutesSlice,
  ContainerExposedRepositoriesSlice,
  ContainerForgotPasswordSlice,
  ContainerInfraSlice,
  ContainerInboundWebhookRoutesSlice,
  ContainerInternalCronRoutesSlice,
  ContainerInternalIdentityEmailRoutesSlice,
  ContainerInternalIdentitySubjectUsageRoutesSlice,
  ContainerKycRoutesSlice,
  ContainerLegalEntityMemberRoutesSlice,
  ContainerLegalEntityRoutesSlice,
  ContainerLotCatalogSlice,
  ContainerLotDocumentRoutesSlice,
  ContainerLotLifecycleSlice,
  ContainerLotReadRoutesSlice,
  ContainerLotRouteDepsSlice,
  ContainerLotRoutesSlice,
  ContainerLotSaleSlice,
  ContainerMarketingRoutesSlice,
  ContainerNewsletterRoutesSlice,
  ContainerOnsiteEventRoutesSlice,
  ContainerOnsiteEventSlice,
  ContainerOrganizationOnboardingRoutesSlice,
  ContainerOrganizationRoutesSlice,
  ContainerPasswordStepUpSlice,
  ContainerPaymentHttpRoutesSlice,
  ContainerPaymentsSlice,
  ContainerPayoutRoutesSlice,
  ContainerPayoutStatementRoutesSlice,
  ContainerPlatformSlice,
  ContainerPostmarkWebhookRoutesSlice,
  ContainerPressRoutesSlice,
  ContainerQrRoutesSlice,
  ContainerRepositoriesSlice,
  ContainerRootSlice,
  ContainerSaleDocumentRoutesSlice,
  ContainerSaleRegistrationSlice,
  ContainerSaleroomDisplayRoutesSlice,
  ContainerStripeConnectRoutesSlice,
  ContainerStripeWebhookRoutesSlice,
  ContainerSubmissionDocumentRoutesSlice,
  ContainerSubmissionRoutesSlice,
  ContainerTelephoneBookingRoutesSlice,
  ContainerBuyerTelephoneBookingRoutesSlice,
  ContainerAdminTelephoneBookingRoutesSlice,
  ContainerUploadRoutesSlice,
  ContainerUserMiscSlice,
  ContainerUserProfileSlice,
  ContainerUserAccountRoutesSlice,
  ContainerUserRouteServicesSlice,
  ContainerUserSuspensionExposureSlice,
  ContainerUserUtilitySlice,
  ContainerVenueRoutesSlice,
  ContainerVeriffWebhookRoutesSlice,
  ContainerXeroWebhookRoutesSlice,
  ContainerSaleAuxRoutesSlice,
  ContainerSaleFollowRoutesSlice,
  ContainerSaleLifecycleWriteRoutesSlice,
  ContainerSaleLotMembershipRoutesSlice,
  ContainerSaleReadRoutesSlice,
  ContainerSaleRoutesSlice,
  LotLifecyclePort,
  LotReadPort,
  SaleLifecycleWritePort,
  SaleLookupPort,
  SaleLotMembershipPort,
  SaleReadPort,
  SaleroomReadPort,
  TelephoneBookingRoutePort,
  TelephoneBidBookingServicePort,
} from "./container/container-slices.js";
