import { createDb } from "@auction/db";
import type { Container, ContainerComposedSlices } from "./container/container-slices.js";
import { createAdminServices } from "./container/create-admin-services.js";
import { createAuthRepositories } from "./container/create-auth-repositories.js";
import { createContainerAuth } from "./container/create-auth.js";
import { createBiddingRouteServices } from "./container/create-bidding-route-services.js";
import { createBiddingSaleroom } from "./container/create-bidding-saleroom.js";
import { createCatalogServices } from "./container/create-catalog-services.js";
import { createComplianceMedia } from "./container/create-compliance-media.js";
import { createCronServices } from "./container/create-cron-services.js";
import { createInfra } from "./container/create-infra.js";
import { createLotLifecycle } from "./container/create-lot-lifecycle.js";
import { createPaymentsServices } from "./container/create-payments-services.js";
import { createPlatformServices } from "./container/create-platform-services.js";
import { createRepositories } from "./container/create-repositories.js";
import { createUserMiscServices } from "./container/create-user-misc-services.js";
import type { Env } from "./env.js";
import { EnsurePersonalLegalEntityService } from "./services/legal-entity/ensure-personal-legal-entity.service.js";
import { SessionRevocationService } from "./services/session-revocation.service.js";

export type { Container, ContainerComposedSlices };

export function createContainer(env: Env): Container {
  const db = createDb(env.DATABASE_URL_API ?? env.DATABASE_URL);
  const authDb = createDb(env.DATABASE_URL_AUTH ?? env.DATABASE_URL);
  const infra = createInfra(env, db, authDb);

  const { sessionRepository } = createAuthRepositories(authDb);
  const sessionRevocation = new SessionRevocationService(sessionRepository);
  const ensurePersonalLegalEntityService = new EnsurePersonalLegalEntityService(db);
  const { auth, authenticator } = createContainerAuth({
    env,
    db,
    authDb,
    emailService: infra.emailService,
    sessionRevocation,
    ensurePersonalLegalEntityService,
  });

  const repos = createRepositories(db);

  const platform = createPlatformServices({ env, db, infra, repos });
  const lotLifecycle = createLotLifecycle({ infra, repos, platform });
  const complianceMedia = createComplianceMedia({ env, db, infra, repos, platform });
  const catalog = createCatalogServices({
    env,
    db,
    infra,
    repos,
    platform,
    lotLifecycle,
    complianceMedia,
  });
  const payments = createPaymentsServices({
    env,
    db,
    infra,
    repos,
    platform,
    complianceMedia,
    catalog,
  });
  const biddingSaleroom = createBiddingSaleroom({
    env,
    db,
    infra,
    repos,
    platform,
    lotLifecycle,
    complianceMedia,
    catalog,
    payments,
  });
  const userMisc = createUserMiscServices({
    env,
    db,
    authDb,
    auth,
    sessionRevocation,
    ensurePersonalLegalEntityService,
    infra,
    repos,
    platform,
    complianceMedia,
    catalog,
    payments,
  });
  const admin = createAdminServices({
    env,
    db,
    infra,
    repos,
    platform,
    complianceMedia,
    catalog,
    payments,
    bidding: biddingSaleroom,
    userMisc,
  });
  const cron = createCronServices({
    env,
    db,
    authDb,
    infra,
    repos,
    platform,
    payments,
    catalog,
    lotLifecycle,
    biddingSaleroom,
    complianceMedia,
  });

  return {
    env,
    db,
    authDb,
    sessionRevocation,
    redis: infra.redis,
    rateLimitStore: infra.rateLimitStore,
    vapidPublicKey: env.VAPID_PUBLIC_KEY ?? null,
    auth,
    getPublicJwks: infra.getPublicJwks,
    authenticator,
    repoFactory: repos.repoFactory,
    lotService: catalog.lotService,
    conditionReportService: catalog.conditionReportService,
    saleService: catalog.saleService,
    saleListReadService: catalog.saleListReadService,
    pressArchiveReadService: catalog.pressArchiveReadService,
    saleSoftDeleteService: catalog.saleSoftDeleteService,
    lotSoftDeleteService: catalog.lotSoftDeleteService,
    saleFollowService: catalog.saleFollowService,
    saleBiddersService: catalog.saleBiddersService,
    saleRegistrationService: biddingSaleroom.saleRegistrationService,
    lotLifecycleService: lotLifecycle.lotLifecycleService,
    lotLifecycleQueryService: catalog.lotLifecycleQueryService,
    lotTransitionOrchestrator: catalog.lotTransitionOrchestrator,
    adminLotBrowseService: catalog.adminLotBrowseService,
    absenteeBidService: biddingSaleroom.absenteeBidService,
    telephoneBidBookingService: catalog.telephoneBidBookingService,
    paddleService: catalog.paddleService,
    saleroomCheckInService: catalog.saleroomCheckInService,
    onsiteEventPublicRsvpService: catalog.onsiteEventPublicRsvpService,
    onsiteEventAdminService: catalog.onsiteEventAdminService,
    onsiteEventPassService: catalog.onsiteEventPassService,
    onsiteEventStaffCheckInService: catalog.onsiteEventStaffCheckInService,
    adminSaleOperationsSnapshotService: biddingSaleroom.adminSaleOperationsSnapshotService,
    saleroomService: biddingSaleroom.saleroomService,
    displayPairingService: biddingSaleroom.displayPairingService,
    displayOverlayService: biddingSaleroom.displayOverlayService,
    displaySnapshotReader: biddingSaleroom.displaySnapshotReader,
    saleroomOnBlockPolicy: biddingSaleroom.saleroomOnBlockPolicy,
    lotFulfilmentService: payments.lotFulfilmentService,
    saleLifecycleService: lotLifecycle.saleLifecycleService,
    lotJobScheduler: catalog.lotJobScheduler,
    saleStatusTransitionService: catalog.saleStatusTransitionService,
    bidService: biddingSaleroom.bidService,
    autoBidService: biddingSaleroom.autoBidService,
    categoryService: catalog.categoryService,
    venueService: catalog.venueService,
    resolvePlatformCatalogLegalEntityId: catalog.resolvePlatformCatalogLegalEntityId,
    artistProfileService: catalog.artistProfileService,
    artistDeleteService: catalog.artistDeleteService,
    dashboardQueryService: catalog.dashboardQueryService,
    userDashboardReadService: userMisc.userDashboardReadService,
    cachedCatalogueListService: platform.cachedCatalogueListService,
    notificationQueryService: catalog.notificationQueryService,
    paymentBuyerService: payments.paymentBuyerService,
    paymentAdminService: payments.paymentAdminService,
    paymentMaintenanceService: payments.paymentMaintenanceService,
    lotInvoiceInitiationService: payments.lotInvoiceInitiationService,
    qrCodeService: catalog.qrCodeService,
    qrCodeAnalytics: catalog.qrCodeAnalytics,
    paymentRefundReconcileService: platform.paymentRefundReconcileService,
    accountingProvider: payments.accountingProvider,
    invoiceAddressingService: platform.invoiceAddressingService,
    xeroPayoutBillWriter: payments.xeroPayoutBillWriter,
    xeroPaymentRecorder: payments.xeroPaymentRecorder,
    xeroOAuthService: payments.xeroOAuthService,
    xeroWebhookEventRepository: repos.xeroWebhookEventRepository,
    userService: userMisc.userService,
    watchlistService: userMisc.watchlistService,
    savedSearchService: userMisc.savedSearchService,
    userSecurityReadService: userMisc.userSecurityReadService,
    authCredentialReader: userMisc.authCredentialReader,
    newsletterSignupService: userMisc.newsletterSignupService,
    webhookEventRepository: repos.webhookEventRepository,
    artistWatchlistService: userMisc.artistWatchlistService,
    notificationService: platform.notificationService,
    notificationPreferenceRepository: repos.notificationPreferenceRepository,
    uiPreferenceRepository: repos.uiPreferenceRepository,
    uiPreferenceService: platform.uiPreferenceService,
    pushSubscriptionRepository: repos.pushSubscriptionRepository,
    notificationDispatcher: platform.notificationDispatcher,
    notificationOutboxProcessor: platform.notificationOutboxProcessor,
    notificationFactory: platform.notificationFactory,
    emailService: infra.emailService,
    emailObservabilityRepository: repos.emailObservabilityRepository,
    userSuspensionChecker: platform.cachedUserSuspensionChecker,
    userSuspensionCacheInvalidator: platform.cachedUserSuspensionChecker,
    registrationService: userMisc.registrationService,
    invitationService: userMisc.invitationService,
    profileService: userMisc.profileService,
    addressService: userMisc.addressService,
    analyticsService: userMisc.analyticsService,
    domainEventSink: platform.domainEventSink,
    transactionRunner: platform.transactionRunner,
    authAuditPublisher: platform.authAuditPublisher,
    legalEntityLifecycleAdminService: platform.legalEntityLifecycleAdminService,
    legalEntityDocumentAdminService: complianceMedia.legalEntityDocumentAdminService,
    impersonationAuditService: platform.impersonationAuditService,
    impersonationSessionService: platform.impersonationSessionService,
    legalEntityAccessService: platform.legalEntityAccessService,
    requireLegalEntityContext: platform.requireLegalEntityContext,
    requireSubmissionsLegalEntityContext: userMisc.requireSubmissionsLegalEntityContext,
    adminUserService: userMisc.adminUserService,
    adminNavCountsService: admin.adminNavCountsService,
    adminLotsKpiTrendService: admin.adminLotsKpiTrendService,
    adminPaymentsKpiTrendService: admin.adminPaymentsKpiTrendService,
    adminSalesKpiTrendService: admin.adminSalesKpiTrendService,
    adminPayoutsKpiTrendService: admin.adminPayoutsKpiTrendService,
    adminPaymentListQueryService: userMisc.adminPaymentListQueryService,
    adminMetricsService: payments.adminMetricsService,
    attentionFeedReader: repos.attentionFeedReader,
    httpErrorHandler: userMisc.httpErrorHandler,
    itemSubmissionRepository: repos.itemSubmissionRepository,
    itemSubmissionService: catalog.itemSubmissionService,
    itemSubmissionSellerApi: catalog.itemSubmissionSellerApi,
    itemSubmissionAdminApi: catalog.itemSubmissionAdminApi,
    userEmailChangeRepository: repos.userEmailChangeRepository,
    legalEntityRepository: repos.legalEntityRepository,
    personalLegalEntityResolver: userMisc.personalLegalEntityResolver,
    legalEntityNotificationRecipients: repos.legalEntityNotificationRecipients,
    kycRepository: repos.kycRepository,
    kycService: complianceMedia.kycService,
    kycResubmissionNotifier: complianceMedia.kycResubmissionNotifier,
    amlService: complianceMedia.amlService,
    sourceOfFundsService: complianceMedia.sourceOfFundsService,
    adminSourceOfFundsQueryService: complianceMedia.adminSourceOfFundsQueryService,
    sourceOfFundsDocumentCollectionService: complianceMedia.sourceOfFundsDocumentCollectionService,
    sourceOfFundsDocumentReviewService: complianceMedia.sourceOfFundsDocumentReviewService,
    organizationOnboardingService: platform.organizationOnboardingService,
    orgModuleGate: userMisc.orgModuleGate,
    organizationOnboardingFlowService: platform.organizationOnboardingFlowService,
    artistRegistryService: platform.artistRegistryService,
    stripeConnectService: platform.stripeConnectService,
    memberManagementService: platform.memberManagementService,
    pendingInvitationsReader: repos.pendingInvitationsReader,
    invitationLifecycleService: platform.invitationLifecycleService,
    transactionalMailer: platform.transactionalMailer,
    payoutRepository: repos.payoutRepository,
    payoutService: platform.payoutService,
    payoutSellerService: platform.payoutSellerService,
    payoutAdminService: platform.payoutAdminService,
    payoutSettlementService: platform.payoutSettlementService,
    payoutMaintenanceService: platform.payoutMaintenanceService,
    objectStorage: infra.objectStorage,
    mediaUrlResolver: complianceMedia.mediaUrlResolver,
    mediaAssetEnricher: complianceMedia.mediaAssetEnricher,
    uploadService: complianceMedia.uploadService,
    lotDocumentService: complianceMedia.lotDocumentService,
    saleDocumentService: complianceMedia.saleDocumentService,
    submissionDocumentService: complianceMedia.submissionDocumentService,
    uploadValidationQueue: infra.uploadValidationQueue,
    imageCleanupQueue: infra.imageCleanupQueue,
    marketingSyncQueue: infra.marketingSyncQueue,
    payoutStatementQueue: infra.payoutStatementQueue,
    dataExportQueue: infra.dataExportQueue,
    exportService: complianceMedia.exportService,
    legalEntityArchiveQueue: infra.legalEntityArchiveQueue,
    stripePaymentWebhookService: payments.stripePaymentWebhookService,
    stripeClientFactory: infra.stripeClientFactory,
    stripeWebhookVerifier: infra.stripeWebhookVerifier,
    marketingEventService: complianceMedia.marketingEventService,
    marketingEventPublisher: complianceMedia.marketingEventPublisher,
    clickIdStore: complianceMedia.clickIdStore,
    postmarkWebhookService: userMisc.postmarkWebhookService,
    brevoWebhookIngestService: cron.brevoWebhookIngestService,
    accountDeletionEligibilityService: cron.accountDeletionEligibilityService,
    settlementCronService: cron.settlementCronService,
    accountingReplayCronService: cron.accountingReplayCronService,
    paymentMaintenanceCronService: cron.paymentMaintenanceCronService,
    lifecycleCronService: cron.lifecycleCronService,
    hygieneCronService: cron.hygieneCronService,
    adminMarketingEventsService: userMisc.adminMarketingEventsService,
    emailUnsubscribeService: userMisc.emailUnsubscribeService,
    bidding: createBiddingRouteServices({
      absenteeBidService: biddingSaleroom.absenteeBidService,
      autoBidService: biddingSaleroom.autoBidService,
      conditionReportService: catalog.conditionReportService,
    }),
    admin: admin.admin,
    queueAdmin: userMisc.queueAdmin,
    closeBullQueues: userMisc.closeBullQueues,
  };
}

export type {
  ContainerAdminMarketingEventsRoutesSlice,
  ContainerAdminOnsiteEventRoutesSlice,
  ContainerAdminPayoutRoutesSlice,
  ContainerAdminPlatformRoutesSlice,
  ContainerAdminQueuesRoutesSlice,
  ContainerAdminRoutesSlice,
  ContainerAdminSlice,
  ContainerArtistRoutesSlice,
  ContainerAuthRoutesSlice,
  ContainerBidRoutesSlice,
  ContainerBiddingRoutesSlice,
  ContainerBiddingSaleroomSlice,
  ContainerBrevoWebhookRoutesSlice,
  ContainerCatalogAdminReadersSlice,
  ContainerCatalogSlice,
  ContainerCategoryRoutesSlice,
  ContainerComplianceMediaSlice,
  ContainerCredentialSetupSlice,
  ContainerCronSlice,
  ContainerEmailRoutesSlice,
  ContainerExportRoutesSlice,
  ContainerExposedRepositoriesSlice,
  ContainerForgotPasswordSlice,
  ContainerInfraSlice,
  ContainerInboundWebhookClaimRoutesSlice,
  ContainerInboundWebhookRoutesSlice,
  ContainerInternalCronRoutesSlice,
  ContainerKycRoutesSlice,
  ContainerLegalEntityMemberRoutesSlice,
  ContainerLegalEntityRoutesSlice,
  ContainerLotCatalogSlice,
  ContainerLotDocumentRoutesSlice,
  ContainerLotLifecycleSlice,
  ContainerLotRouteDepsSlice,
  ContainerLotRoutesSlice,
  ContainerLotSaleSlice,
  ContainerMarketingRoutesSlice,
  ContainerNewsletterRoutesSlice,
  ContainerOnsiteEventRoutesSlice,
  ContainerOnsiteEventSlice,
  ContainerOrganizationOnboardingRoutesSlice,
  ContainerOrganizationRoutesSlice,
  ContainerPasswordStepUpSlice,
  ContainerPaymentExposureSlice,
  ContainerPaymentHttpRoutesSlice,
  ContainerPaymentRoutesSlice,
  ContainerPaymentsSlice,
  ContainerPayoutRoutesSlice,
  ContainerPayoutStatementRoutesSlice,
  ContainerPlatformSlice,
  ContainerPostmarkWebhookRoutesSlice,
  ContainerPressRoutesSlice,
  ContainerQrRoutesSlice,
  ContainerRepositoriesSlice,
  ContainerRootSlice,
  ContainerSaleDocumentRoutesSlice,
  ContainerSaleRegistrationSlice,
  ContainerSaleroomDisplayRoutesSlice,
  ContainerStripeConnectRoutesSlice,
  ContainerStripeWebhookRoutesSlice,
  ContainerSubmissionDocumentRoutesSlice,
  ContainerSubmissionRoutesSlice,
  ContainerTelephoneBookingRoutesSlice,
  ContainerUploadRoutesSlice,
  ContainerUserMiscSlice,
  ContainerUserProfileSlice,
  ContainerUserRoutesSlice,
  ContainerUserSuspensionExposureSlice,
  ContainerUserUtilitySlice,
  ContainerVenueRoutesSlice,
  ContainerVeriffWebhookRoutesSlice,
  ContainerXeroWebhookRoutesSlice,
  ContainerSaleRoutesSlice,
  ContainerWellKnownRoutesSlice,
} from "./container/container-slices.js";
