export type {
  IRepositoryFactory,
  LotBidRepos,
  TransactionRepos,
} from "./repository-factory.js";
export { DrizzleRepositoryFactory } from "./drizzle-repository.factory.js";
export { DrizzleTransactionRunner, type ITransactionRunner } from "./transaction-runner.js";

export type {
  ArchiveEndedAggregateFilter,
  ListLotsFilter,
  ListLotsSort,
  ListSalesFilter,
  ListSalesSort,
  ILotAnalyticsRepository,
  ILotLifecycleRepository,
  ILotReadRepository,
  ILotRepository,
  ILotWriteRepository,
  ListCatalogLotsBySalePageInput,
  SaleCatalogLotsSort,
  ISaleRepository,
  CreateBidRow,
  IBidRepository,
  IItemSubmissionRepository,
  ItemSubmissionUpdatePatch,
  ListSubmissionsFilter,
  ISessionRepository,
  AuthSessionListRow,
  IAuthCredentialReader,
  IUserEmailChangeRepository,
  EmailChangeConfirmFailureKind,
  EmailChangeConfirmPayload,
  IImpersonationSessionRepository,
  ImpersonationDbClient,
  ImpersonationEndReason,
  ImpersonationSessionRow,
  IEmailSuppressionRepository,
  IEmailWebhookIngestRepository,
  INewsletterSignupRepository,
  IWebhookEventRepository,
  IUploadObjectReader,
  IUploadPersistenceRepository,
  InsertPendingUploadInput,
  UploadObjectRow,
  ISavedSearchRepository,
  SavedSearchRow,
  IAccountDeletionEligibilityReader,
  AbsenteeBidRow,
  IAbsenteeBidRepository,
  BidLotRulesRow,
  IBidLotRulesReader,
  IBidMembershipReader,
  BuyerAgentAuthorisationRow,
  IBuyerAgentAuthorisationReader,
  IGuestPaddleReader,
  IPaddleRepository,
  PaddleRegistrationRow,
  IPaddleBidWindowReader,
  IOperatorPlacementReader,
  OperatorPlacementPaddleRegistrationRow,
  TelephoneBookingCapRow,
  TelephoneBookingPlacementRow,
  ISaleroomDisplaySessionRepository,
  ISaleroomSessionRepository,
  SaleroomEventKind,
  SaleroomEventRow,
  SaleroomSessionRow,
  SaleroomSessionStatusSummary,
  ITelephoneBookingUserPhoneReader,
  TelephoneBookingUserPhoneRow,
  ISaleRegistrationBidReader,
  SaleRegistrationBidRow,
  ISaleRegistrationCheckInReader,
  SaleCheckInGateRow,
  UserCheckInGateRow,
  IOnsiteEventCheckInLogRepository,
  InsertOnsiteEventCheckInLogInput,
  IOnsiteEventClientReader,
  OnsiteEventClientRow,
  ILotLifecycleSnapshotReader,
  ILotLifecycleSnapshotRepository,
  LotLifecycleSnapshotPatch,
  LotLifecycleSnapshotRow,
  LotLifecycleTimelineEventRow,
  UpsertLotLifecycleSnapshotInput,
  ILotLifecycleTimelineReader,
  ILotTransitionGuardReader,
  LotTransitionGuardCounts,
  ILotTransitionRepository,
  AdminDisputePaymentRow,
  IAdminDisputeCaseEnrichmentReader,
  IAdminMarketingEventOutboxRepository,
  MarketingEventOutboxFailedHourRow,
  MarketingEventOutboxState,
  MarketingEventOutboxStatsRow,
  AdminSaleOperationsCurrentLotBidding,
  AdminSaleOperationsCurrentLotRow,
  AdminSaleOperationsSaleRow,
  AdminSaleOperationsSessionRow,
  IAdminSaleOperationsSnapshotReader,
  ConnectTransferLegalEntity,
  IConnectTransferRepository,
  IPaymentRefundReconcileRepository,
  PaymentRefundReconcilePayload,
  PaymentRefundReconcileRow,
  IQrCodeAnalyticsReader,
  QrCodeAnalyticsRange,
  QrCodeBreakdownAggregateRow,
  QrCodeDailyAggregates,
  QrCodeDailyTrendRow,
  QrCodeRawAggregates,
  QrCodeRawRecentScanRow,
  QrCodeRawTrendRow,
  ISourceOfFundsDocumentReviewRepository,
  SourceOfFundsDocumentChecks,
  SourceOfFundsDocumentReviewRow,
  ISourceOfFundsSettlementReader,
  SofBatchPaymentSettlementRow,
  SofBatchWonUnpaidLotSaleRow,
  SofBlockedPaymentRow,
  SofPaymentSettlementRow,
  SofWonUnpaidLotSaleRow,
  ILegalEntityDocumentAdminRepository,
  LegalEntityDocumentAdminRow,
  ILegalEntityLifecycleAdminRepository,
  LegalEntityLifecycleRow,
  LegalEntityLifecycleTransitionUpdate,
} from "./interfaces/index.js";

export {
  EmailChangeConfirmError,
  ACTIVE_BUYER_SETTLEMENT_PAYMENT_STATUSES,
} from "./interfaces/index.js";

export {
  DrizzleLotRepository,
  DrizzleBidRepository,
  DrizzleSaleRepository,
  DrizzleItemSubmissionRepository,
  DrizzleSessionRepository,
  DrizzleAuthCredentialReader,
  DrizzleUserEmailChangeRepository,
  DrizzleImpersonationSessionRepository,
  DrizzleEmailSuppressionRepository,
  DrizzleEmailWebhookIngestRepository,
  DrizzleNewsletterSignupRepository,
  DrizzleWebhookEventRepository,
  DrizzleUploadObjectReader,
  DrizzleUploadPersistenceRepository,
  DrizzleSavedSearchRepository,
  DrizzleAccountDeletionEligibilityReader,
  DrizzleAbsenteeBidRepository,
  DrizzleBidLotRulesReader,
  DrizzleBidMembershipReader,
  DrizzleBuyerAgentAuthorisationReader,
  DrizzleGuestPaddleReader,
  DrizzlePaddleRepository,
  isPaddleUniqueViolation,
  DrizzlePaddleBidWindowReader,
  DrizzleOperatorPlacementReader,
  DrizzleSaleroomDisplaySessionRepository,
  DrizzleSaleroomSessionRepository,
  DrizzleTelephoneBookingUserPhoneReader,
  DrizzleSaleRegistrationBidReader,
  DrizzleSaleRegistrationCheckInReader,
  DrizzleOnsiteEventCheckInLogRepository,
  DrizzleOnsiteEventClientReader,
  DrizzleLotLifecycleSnapshotRepository,
  DrizzleLotLifecycleTimelineReader,
  DrizzleLotTransitionGuardReader,
  createDrizzleLotTransitionRepository,
  DrizzleLotTransitionRepository,
  DrizzleAdminDisputeCaseEnrichmentReader,
  DrizzleAdminMarketingEventOutboxRepository,
  DrizzleAdminSaleOperationsSnapshotReader,
  DrizzleConnectTransferRepository,
  DrizzlePaymentRefundReconcileRepository,
  listPaymentsMissingXeroInvoice,
  listPendingStripeCaptureSync,
  type MissingXeroInvoiceRow,
  type PendingStripeCaptureSyncRow,
  DrizzleQrCodeAnalyticsReader,
  DrizzleSourceOfFundsDocumentReviewRepository,
  DrizzleSourceOfFundsSettlementReader,
  DrizzleLegalEntityDocumentAdminRepository,
  DrizzleLegalEntityLifecycleAdminRepository,
} from "./repositories/index.js";

export {
  mapLotRow,
  mapBidRow,
  mapSaleRow,
  mapItemSubmissionRow,
} from "./lib/entity-row-mappers.js";

export { mergeLotMarketingDetailsPatch } from "./lib/lot-marketing-details-merge.js";

export { queryCreatedAtDailyCounts } from "./repositories/created-at-daily-count.query.js";

export {
  EnsurePersonalLegalEntityService,
  type EnsurePersonalLegalEntityInput,
  type EnsurePersonalLegalEntityResult,
  type IEnsurePersonalLegalEntityService,
} from "./services/ensure-personal-legal-entity.js";

export {
  endYearBoundsUtc,
  publicParentSaleExists,
  listWhere as lotListWhere,
  catalogSalePageOrderBy,
  catalogLotsBySaleWhere,
  listOrderBy as lotListOrderBy,
  type ListWhereInput,
} from "./repositories/lot/lot-list-filters.js";
