export type {
  IRepositoryFactory,
  LotBidRepos,
  TransactionRepos,
} from "./repository-factory.js";
export { DrizzleRepositoryFactory } from "./drizzle-repository.factory.js";
export { DrizzleTransactionRunner, type ITransactionRunner } from "./transaction-runner.js";

export type {
  ArchiveEndedAggregateFilter,
  ListLotsFilter,
  ListLotsSort,
  ListSalesFilter,
  ListSalesSort,
  ILotAnalyticsRepository,
  ILotLifecycleRepository,
  ILotReadRepository,
  ILotRepository,
  ILotWriteRepository,
  ListCatalogLotsBySalePageInput,
  SaleCatalogLotsSort,
  ISaleRepository,
  CreateBidRow,
  IBidRepository,
  IItemSubmissionRepository,
  ItemSubmissionUpdatePatch,
  ListSubmissionsFilter,
  ISessionRepository,
  AuthSessionListRow,
  IAuthCredentialReader,
  IUserEmailChangeRepository,
  EmailChangeConfirmFailureKind,
  EmailChangeConfirmPayload,
  IImpersonationSessionRepository,
  ImpersonationDbClient,
  ImpersonationEndReason,
  ImpersonationSessionRow,
  IEmailSuppressionRepository,
  IEmailWebhookIngestRepository,
  INewsletterSignupRepository,
  IWebhookEventRepository,
  IUploadObjectReader,
  IUploadPersistenceRepository,
  InsertPendingUploadInput,
  UploadObjectRow,
  ISavedSearchRepository,
  SavedSearchRow,
  IAccountDeletionEligibilityReader,
  AbsenteeBidRow,
  IAbsenteeBidRepository,
  BidLotRulesRow,
  IBidLotRulesReader,
  IBidMembershipReader,
  BuyerAgentAuthorisationRow,
  IBuyerAgentAuthorisationReader,
  IGuestPaddleReader,
  IPaddleRepository,
  PaddleRegistrationRow,
  IPaddleBidWindowReader,
  IOperatorPlacementReader,
  OperatorPlacementPaddleRegistrationRow,
  TelephoneBookingCapRow,
  TelephoneBookingPlacementRow,
  ISaleroomDisplaySessionRepository,
  ISaleroomSessionRepository,
  SaleroomEventKind,
  SaleroomEventRow,
  SaleroomSessionRow,
  SaleroomSessionStatusSummary,
  ITelephoneBookingUserPhoneReader,
  TelephoneBookingUserPhoneRow,
  ISaleRegistrationBidReader,
  SaleRegistrationBidRow,
  ISaleRegistrationCheckInReader,
  SaleCheckInGateRow,
  UserCheckInGateRow,
  ISaleRegistrationRepository,
  InsertSaleRegistrationInput,
  SaleRegistrationAdminRow,
  SaleRegistrationRow,
  ITelephoneBidBookingRepository,
  InsertTelephoneBidBookingRow,
  TelephoneBidBookingAdminRow,
  TelephoneBidBookingRow,
  ITelephoneBidBookingDetailReader,
  TelephoneBidBookingDetail,
  BuyerConditionReportListRow,
  ConditionReportAdminListFilter,
  ConditionReportRequestListRow,
  ConditionReportRequestRow,
  IConditionReportRequestRepository,
  InsertConditionReportRequestInput,
  UpdateConditionReportRequestInput,
  IOnsiteEventCheckInLogRepository,
  InsertOnsiteEventCheckInLogInput,
  CreateOnsiteEventInput,
  IOnsiteEventRepository,
  UpdateOnsiteEventInput,
  IOnsiteEventRsvpRepository,
  OnsiteEventRsvpWithGuest,
  UpdateOnsiteEventCheckInTokenInput,
  UpsertOnsiteEventRsvpInput,
  ISaleExpectedGuestsReader,
  CheckInCandidateEntity,
  CheckInCandidateRow,
  CheckInWithPaddleInput,
  CheckInWithPaddleResult,
  ISaleroomCheckInRepository,
  IOnsiteEventClientReader,
  OnsiteEventClientRow,
  ILotLifecycleSnapshotReader,
  ILotLifecycleSnapshotRepository,
  LotLifecycleSnapshotPatch,
  LotLifecycleSnapshotRow,
  LotLifecycleTimelineEventRow,
  UpsertLotLifecycleSnapshotInput,
  ILotLifecycleTimelineReader,
  ILotTransitionGuardReader,
  LotTransitionGuardCounts,
  ILotTransitionRepository,
  AdminDisputePaymentRow,
  IAdminDisputeCaseEnrichmentReader,
  IAdminMarketingEventOutboxRepository,
  MarketingEventOutboxFailedHourRow,
  MarketingEventOutboxState,
  MarketingEventOutboxStatsRow,
  AdminSaleOperationsCurrentLotBidding,
  AdminSaleOperationsCurrentLotRow,
  AdminSaleOperationsSaleRow,
  AdminSaleOperationsSessionRow,
  IAdminSaleOperationsSnapshotReader,
  ConnectTransferLegalEntity,
  IConnectTransferRepository,
  IPaymentRefundReconcileRepository,
  PaymentRefundReconcilePayload,
  PaymentRefundReconcileRow,
  IQrCodeAnalyticsReader,
  QrCodeAnalyticsRange,
  QrCodeBreakdownAggregateRow,
  QrCodeDailyAggregates,
  QrCodeDailyTrendRow,
  QrCodeRawAggregates,
  QrCodeRawRecentScanRow,
  QrCodeRawTrendRow,
  ISourceOfFundsDocumentReviewRepository,
  SourceOfFundsDocumentChecks,
  SourceOfFundsDocumentReviewRow,
  ISourceOfFundsSettlementReader,
  SofBatchPaymentSettlementRow,
  SofBatchWonUnpaidLotSaleRow,
  SofBlockedPaymentRow,
  SofPaymentSettlementRow,
  SofWonUnpaidLotSaleRow,
  ILegalEntityDocumentAdminRepository,
  LegalEntityDocumentAdminRow,
  ILegalEntityLifecycleAdminRepository,
  LegalEntityLifecycleRow,
  LegalEntityLifecycleTransitionUpdate,
  CreateAddressInput,
  IAddressRepository,
  IProfileReader,
  IProfileWriter,
  ProfileMeRow,
  ProfileUpdateInput,
  UpdateAddressInput,
  UserAddressRow,
  IUserRepository,
  UserProfileRow,
  IUserSuspensionChecker,
  IUiPreferenceRepository,
  UiPreferenceRow,
  CreatePushSubscriptionRow,
  IPushSubscriptionRepository,
  IWatchlistRepository,
  WatchlistListPageInput,
  WatchlistPageSort,
  WatchlistRow,
  ArtistWatchlistRow,
  IArtistWatchlistRepository,
  INotificationReadRepository,
  NotificationListFilter,
  NotificationListTab,
  CreateNotificationRow,
  INotificationWriteRepository,
  INotificationOutboxRepository,
  NotificationOutboxRow,
  NotificationPayload,
  StageNotificationOutboxInput,
  INotificationPreferenceReader,
  INotificationPreferenceRepository,
  INotificationPreferenceWriter,
  NotificationPreferenceInput,
  ISaleFollowRepository,
  SaleFollowRow,
  ISaleBiddersReader,
  SaleBidderRow,
  ISaleModeLookup,
  ISaleroomSessionLookup,
  IVenueRepository,
  ListVenuesFilter,
  VenueListRow,
  CreateCategoryInput,
  ICategoryRepository,
  UpdateCategoryInput,
  ApproveDisplayPairingInput,
  DisplayPairingRow,
  IDisplayPairingRepository,
  InsertDisplayPairingInput,
  EmailEventRow,
  EmailOutboxRow,
  EmailSuppressionRow,
  IEmailObservabilityRepository,
  IEntityDocumentRepository,
  ILotDocumentRepository,
  ISaleDocumentRepository,
  ISubmissionDocumentRepository,
  EntityDocumentPersistedRow,
  ActiveMembership,
  ILegalEntityRepository,
  ILegalEntityMembershipReader,
  ILegalEntityReader,
  ILegalEntityMemberRepository,
  LegalEntityMemberRow,
  MemberConfirmationContext,
  MemberWithUser,
  AttachOnboardingDocumentInput,
  CreateOrganisationAttemptInput,
  ILegalEntityOnboardingRepository,
  OnboardingAddressRow,
  OnboardingDbExecutor,
  OnboardingDocumentRow,
  OnboardingOrganisationRow,
  ILegalEntityConnectReader,
  ILegalEntityConnectRepository,
  ILegalEntityNotificationRecipientReader,
  LegalEntityNotificationAudience,
  EntityInvitationCreate,
  EntityMemberCreate,
  IEntityInvitationRepository,
  ILotSoftDeleteGuardReader,
  LotSoftDeleteGuardCounts,
  ISaleSoftDeleteGuardReader,
  SaleSoftDeleteGuardCounts,
  CreateKycVerificationInput,
  IKycSessionRepository,
  UpdateKycVerificationPatch,
  IKycRepository,
  AntiShillingBidContext,
  IAntiShillingGuard,
  IPendingInvitationsReader,
  PendingInvitationView,
  ConsumeInviteResult,
  InvitationAdminListFilters,
  InvitationAdminListRow,
  InvitationInsert,
  InvitationRow,
  InvitationSummary,
  IUserInvitationRepository,
  AdminPaymentTableRowDto,
  AdminPaymentsSummaryStats,
  CreatePaymentRow,
  IPaymentAnalyticsRepository,
  IPaymentLifecycleRepository,
  IPaymentMutationRepository,
  IPaymentReadRepository,
  IPaymentWriteRepository,
  ListPaymentsAdminTableFilter,
  ListPaymentsExportFilter,
  PaymentRecord,
  CreatePayoutInput,
  InsertPayoutLineInput,
  IPayoutAnalyticsRepository,
  IPayoutLifecycleRepository,
  IPayoutReadRepository,
  IPayoutRepository,
  IPayoutWriteRepository,
  ListPayoutsFilter,
  PendingPaymentRow,
  ReconcileStripeTransferPatch,
  IPaymentExternalRefRepository,
  IXeroConnectionRepository,
  IXeroWebhookEventRepository,
  PaymentExternalRefInsert,
  PaymentExternalRefRow,
  PaymentExternalSyncStatus,
  XeroConnectionInsert,
  XeroConnectionRow,
  XeroConnectionStatus,
  XeroWebhookEventInsert,
  DateRange,
  ILotMetricsReader,
  IPaymentMetricsReader,
  IUserMetricsReader,
  LotMetricPoint,
  RevenueMetricPoint,
  UserMetricPoint,
  AdminActivityEntry,
  AdminKycSession,
  AdminUserAccountStatus,
  AdminUserBidListResult,
  AdminUserBidRow,
  AdminUserDetail,
  AdminUserListFilter,
  AdminUserListResult,
  AdminUserListRow,
  AdminUserListSort,
  IAdminUserActivityReader,
  IAdminUserBidsReader,
  IAdminUserKycReader,
  IAdminUserReader,
  IAdminUserRoleManager,
  IAdminUserSuspender,
  RedactedDomainEventRow,
  FinanceIssueSnapshot,
  StripeConnectRequirementEntityRow,
  AdminOnboardingLegalEntityRow,
  AdminOnboardingArtistRow,
  AdminOnboardingKycSessionRow,
  AdminOnboardingDocumentRow,
  AdminOnboardingStaleLeadRow,
  AdminOnboardingIssues,
  ManualReviewPaymentBaseRow,
  AdminManualReviewPaymentRow,
  AdminReviewTaskRow,
  IAdminOnboardingIssuesReader,
  IAdminLegalEntityBrowseReader,
  AdminLegalEntityBrowseParams,
  AdminLegalEntityBrowseResult,
  AdminLegalEntityBrowseRow,
  IAdminLotBrowseReader,
  AdminAttachableLotRow,
  AdminLotBrowseInput,
  AdminLotBrowseRawRow,
  AdminLotBrowseState,
  IAdminManualReviewPaymentReader,
  IAdminManualReviewPaymentEnrichmentReader,
  IAdminReviewTaskReader,
  IAdminDomainEventReader,
  IAdminFinanceIssueSnapshotReader,
  AmlDecision,
  AmlDecisionOutcome,
  AmlHoldReason,
  AmlHoldStatus,
  AmlReviewStatus,
  AmlScreeningHit,
  AmlScreeningListing,
  AmlScreeningMatchStatus,
  AmlScreeningMonitorStatus,
  AmlScreeningResult,
  AmlTriageRecommendation,
  AmlWatchlistCategory,
  IAmlHoldStore,
  IWatchlistScreeningReader,
  IWatchlistScreeningWriter,
  UpsertWatchlistScreeningInput,
  WatchlistReviewOutcomeInput,
  WatchlistScreeningRecord,
  WatchlistTriageInput,
  CreateSourceOfFundsCaseInput,
  ISourceOfFundsRepository,
  SourceOfFundsCase,
  SourceOfFundsReviewInput,
  SourceOfFundsStatus,
  SourceOfFundsTriageInput,
  SourceOfFundsTriageRecommendation,
  SourceOfFundsTrigger,
  ISourceOfFundsDocumentRepository,
  SourceOfFundsDocumentReviewStatus,
  SourceOfFundsDocumentRow,
  DbTransaction,
  IArtistDeleteGuards,
  IArtistDeleteRepository,
  ArtistDeleteGuardCounts,
  IArtistExistenceReader,
  AdminArtistListLinkedFilter,
  AdminArtistListOptions,
  AdminArtistListSort,
  IArtistProfileAdminReader,
  IArtistProfileDirectoryReader,
  ArtistProfileCreateInput,
  IArtistProfileCommandRepository,
  UpdateArtistInput,
  IArtistRegistryRepository,
  ArtistRecord,
  ArtistSearchHit,
  ArtistSearchMatchType,
  CreateArtistInput,
  MergeArtistInput,
  MergeArtistResult,
  ReviewArtistInput,
  IQrCodeRepository,
  QrCodeEntityRef,
  QrCodeInsert,
  QrCodeRow,
  QrCodeUpdatePatch,
  QrCodeEntityType,
  QrCodeStatus,
  ExportJobInsert,
  IExportJobRepository,
  ExportJobRow,
  ISaleroomDisplaySnapshotReader,
  SaleroomDisplayCurrentLotRow,
  SaleroomDisplayRecentBidRow,
  SaleroomDisplaySaleRow,
  SaleroomDisplaySessionRow,
  IImpersonationDomainEventReader,
  IPressArchiveRepository,
  ListPressArchiveFilter,
  PressCoveragePageResult,
} from "./interfaces/index.js";

export {
  EmailChangeConfirmError,
  ACTIVE_BUYER_SETTLEMENT_PAYMENT_STATUSES,
  legalEntityNotificationAudienceRoles,
  PaddleTakenError,
} from "./interfaces/index.js";

export {
  DrizzleLotRepository,
  DrizzleBidRepository,
  DrizzleSaleRepository,
  DrizzleItemSubmissionRepository,
  DrizzleSessionRepository,
  DrizzleAuthCredentialReader,
  DrizzleUserEmailChangeRepository,
  DrizzleImpersonationSessionRepository,
  DrizzleEmailSuppressionRepository,
  DrizzleEmailWebhookIngestRepository,
  DrizzleNewsletterSignupRepository,
  DrizzleWebhookEventRepository,
  DrizzleUploadObjectReader,
  DrizzleUploadPersistenceRepository,
  DrizzleSavedSearchRepository,
  DrizzleAccountDeletionEligibilityReader,
  DrizzleAbsenteeBidRepository,
  DrizzleBidLotRulesReader,
  DrizzleBidMembershipReader,
  DrizzleBuyerAgentAuthorisationReader,
  DrizzleGuestPaddleReader,
  DrizzlePaddleRepository,
  isPaddleUniqueViolation,
  DrizzlePaddleBidWindowReader,
  DrizzleOperatorPlacementReader,
  DrizzleSaleroomDisplaySessionRepository,
  DrizzleSaleroomSessionRepository,
  DrizzleTelephoneBookingUserPhoneReader,
  DrizzleSaleRegistrationBidReader,
  DrizzleSaleRegistrationCheckInReader,
  DrizzleSaleRegistrationRepository,
  DrizzleTelephoneBidBookingRepository,
  DrizzleTelephoneBidBookingDetailReader,
  DrizzleConditionReportRequestRepository,
  DrizzleOnsiteEventCheckInLogRepository,
  DrizzleOnsiteEventClientReader,
  DrizzleOnsiteEventRepository,
  DrizzleOnsiteEventRsvpRepository,
  DrizzleSaleroomCheckInRepository,
  DrizzleSaleExpectedGuestsReader,
  DrizzleLotLifecycleSnapshotRepository,
  DrizzleLotLifecycleTimelineReader,
  DrizzleLotTransitionGuardReader,
  createDrizzleLotTransitionRepository,
  DrizzleLotTransitionRepository,
  DrizzleAdminDisputeCaseEnrichmentReader,
  DrizzleAdminMarketingEventOutboxRepository,
  DrizzleAdminSaleOperationsSnapshotReader,
  DrizzleConnectTransferRepository,
  DrizzlePaymentRefundReconcileRepository,
  listPaymentsMissingXeroInvoice,
  listPendingStripeCaptureSync,
  type MissingXeroInvoiceRow,
  type PendingStripeCaptureSyncRow,
  DrizzleQrCodeAnalyticsReader,
  DrizzleQrCodeRepository,
  DrizzleExportJobRepository,
  DrizzleSaleroomDisplaySnapshotReader,
  DrizzleImpersonationDomainEventReader,
  SalePressArchiveRepository,
  DrizzleSourceOfFundsDocumentReviewRepository,
  DrizzleSourceOfFundsSettlementReader,
  DrizzleLegalEntityDocumentAdminRepository,
  DrizzleLegalEntityLifecycleAdminRepository,
  DrizzleProfileRepository,
  DrizzleAddressRepository,
  DrizzleUserRepository,
  DrizzleUserSuspensionChecker,
  DrizzleUiPreferenceRepository,
  DrizzlePushSubscriptionRepository,
  DrizzleWatchlistRepository,
  DrizzleArtistWatchlistRepository,
  DrizzleNotificationReadRepository,
  DrizzleNotificationWriteRepository,
  DrizzleNotificationOutboxRepository,
  NOTIFICATION_OUTBOX_MAX_ATTEMPTS,
  DrizzleNotificationPreferenceRepository,
  DrizzleSaleFollowRepository,
  DrizzleSaleBiddersReader,
  DrizzleSaleModeLookup,
  DrizzleSaleroomSessionLookup,
  DrizzleVenueRepository,
  DrizzleCategoryRepository,
  DrizzleDisplayPairingRepository,
  DrizzleEmailObservabilityRepository,
  DrizzleLotSoftDeleteGuardReader,
  DrizzleSaleSoftDeleteGuardReader,
  DrizzleKycRepository,
  DrizzleAntiShillingRepository,
  DrizzlePendingInvitationsReader,
  DrizzleUserInvitationRepository,
  DrizzlePaymentRepository,
  DrizzlePayoutRepository,
  DrizzlePaymentExternalRefRepository,
  DrizzleXeroConnectionRepository,
  DrizzleXeroWebhookEventRepository,
  DrizzleLotMetricsReader,
  DrizzlePaymentMetricsReader,
  DrizzleUserMetricsReader,
  DrizzleAdminUserReader,
  DrizzleAdminUserRoleManager,
  DrizzleAdminUserActivityReader,
  DrizzleAdminUserBidsReader,
  DrizzleAdminDomainEventReader,
  DrizzleAdminFinanceIssueSnapshotReader,
  DrizzleAdminOnboardingIssuesReader,
  DrizzleAdminLegalEntityBrowseReader,
  DrizzleAdminLotBrowseReader,
  DrizzleAdminManualReviewPaymentReader,
  DrizzleAdminManualReviewPaymentEnrichmentReader,
  DrizzleAdminReviewTaskReader,
  DrizzleLotDocumentRepository,
  DrizzleSaleDocumentRepository,
  DrizzleSubmissionDocumentRepository,
  createDrizzleLegalEntityRepository,
  DrizzleLegalEntityRepository,
  DrizzleLegalEntityReader,
  DrizzleLegalEntityMembershipReader,
  DrizzleLegalEntityMemberRepository,
  DrizzleLegalEntityNotificationRecipientRepository,
  DrizzleLegalEntityOnboardingRepository,
  DrizzleLegalEntityConnectRepository,
  DrizzleEntityInvitationRepository,
  DrizzleInvitationRepository,
  DrizzleAmlHoldStore,
  DrizzleAmlScreeningRepository,
  DrizzleSourceOfFundsRepository,
  DrizzleSourceOfFundsDocumentRepository,
  DrizzleAdminUserKycReader,
  createDrizzleArtistProfileRepository,
  DrizzleArtistProfileRepository,
  DrizzleArtistProfileAdminReader,
  DrizzleArtistProfileCommandRepository,
  DrizzleArtistProfileDirectoryReader,
  DrizzleArtistRegistryRepository,
  insertArtistInTx,
  replaceArtistCategoriesInTx,
  resolveUniqueArtistSlug,
  searchArtists,
  FUZZY_THRESHOLD,
  partialSearchPattern,
  rowToRecord,
  slugify,
} from "./repositories/index.js";

export {
  mapLotRow,
  mapBidRow,
  mapSaleRow,
  mapItemSubmissionRow,
} from "./lib/entity-row-mappers.js";

export { legalEntityRowToDomain } from "./lib/legal-entity-row-mapper.js";
export { rowToLegalEntityMember } from "./lib/legal-entity-member.mapper.js";
export { mapOnsiteEventRow, segmentLabelFor } from "./lib/onsite-event.mapper.js";
export { mapOnsiteEventRsvpRow } from "./lib/onsite-event-rsvp.mapper.js";
export { groupEligibleCheckInEntities } from "./lib/saleroom-check-in-entities.js";
export {
  mapTelephoneBidBookingRow,
  moneyToDbString,
  parseAuthorizedMaxCap,
} from "./lib/telephone-booking.mapper.js";
export {
  OPEN_LOT_STATUSES,
  OPEN_REQUEST_STATUSES,
  extractConditionReportDownloadUrl,
  mapRequestRow,
} from "./lib/condition-report-request.mapper.js";
export {
  mapSaleRegistrationRow,
  toBidLimitString,
  type SaleRegistrationDbRow,
} from "./lib/sale-registration-request.mapper.js";
export { MemberPermissionError } from "./lib/member-permission.error.js";
export {
  assertDocumentsCompleteForSubkind,
  assertEditableStatus,
  ESTATE_CANONICAL_LABELS,
  EDITABLE_ORG_STATUSES,
  isOwnerOrAdmin,
  rowToEntity,
  type OrganizationOnboardingDocumentDto,
  type OrganizationOnboardingFlowOptions,
  type OrganizationOnboardingGetResult,
  type OrganizationOnboardingProfileInput,
  type SubmitForReviewResult,
} from "./lib/org-onboarding-mappers.js";
export type {
  ApplyConnectStatusTransitionInput,
  ConnectAccountCreationContextRow,
  ConnectAddressSnapshot,
  ConnectKycSnapshot,
  LegalEntityConnectRow,
  PersistConnectAccountInput,
  StripeConnectFlagPatch,
} from "./lib/legal-entity-connect.types.js";
export {
  pickEntityAddress,
  pickUserAddress,
  toAddressSnapshot,
} from "./lib/legal-entity-connect.helpers.js";

export { mergeLotMarketingDetailsPatch } from "./lib/lot-marketing-details-merge.js";

export { summarizeVeriffDecision } from "./lib/kyc-decision-summary.js";
export type { KycDecisionSummary } from "./lib/kyc-decision-summary.js";

export { ADMIN_IMPERSONATION_AGGREGATE_TYPE } from "./lib/impersonation-audit.constants.js";

export {
  addMoneyStrings,
  computeLotQueue,
  parseDisplayLotEstimate,
  type CatalogLotRow,
} from "./lib/display-snapshot-reader.helpers.js";

export {
  defaultNotificationPreference,
  emailPreferenceKey,
  inAppPreferenceKey,
  notificationTypeToTemplate,
  pushPreferenceKey,
  whatsappPreferenceKey,
} from "./lib/notification-preference-keys.js";

export { queryCreatedAtDailyCounts } from "./repositories/created-at-daily-count.query.js";

export {
  EnsurePersonalLegalEntityService,
  type EnsurePersonalLegalEntityInput,
  type EnsurePersonalLegalEntityResult,
  type IEnsurePersonalLegalEntityService,
} from "./services/ensure-personal-legal-entity.js";

export {
  endYearBoundsUtc,
  publicParentSaleExists,
  listWhere as lotListWhere,
  catalogSalePageOrderBy,
  catalogLotsBySaleWhere,
  listOrderBy as lotListOrderBy,
  type ListWhereInput,
} from "./repositories/lot/lot-list-filters.js";
