import {
  CLEANUP_DISPLAY_PAIRINGS_QUEUE_NAME,
  ENSURE_LOT_INVOICES_QUEUE_NAME,
  EXPIRE_STALE_PAYMENTS_QUEUE_NAME,
  REFRESH_XERO_TOKENS_QUEUE_NAME,
  RETRY_REFUND_RECONCILES_QUEUE_NAME,
  RETRY_XERO_INVOICE_CREATION_QUEUE_NAME,
  RETRY_XERO_STRIPE_CAPTURE_SYNC_QUEUE_NAME,
  RETRY_XERO_WEBHOOK_FAILURES_QUEUE_NAME,
} from "../queue-names-finance-cron.js";
import type { QueueDefinition } from "../types.js";

/** Worker-scheduled finance HTTP cron proxies (consumer worker → API internal/jobs). */
export const FINANCE_CRON_QUEUE_REGISTRY = {
  [EXPIRE_STALE_PAYMENTS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "high",
    pauseOrder: null,
    heartbeatKey: "expire-stale-payments",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 30_000 },
      removeOnComplete: 50,
      removeOnFail: 50,
    },
    description: "Expire stale buyer payments (API cron proxy)",
  },
  [RETRY_XERO_WEBHOOK_FAILURES_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: "retry-xero-webhook-failures",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 60_000 },
      removeOnComplete: 50,
      removeOnFail: 50,
    },
    description: "Replay failed Xero webhook invoice sync",
  },
  [RETRY_XERO_STRIPE_CAPTURE_SYNC_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: "retry-xero-stripe-capture-sync",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 60_000 },
      removeOnComplete: 50,
      removeOnFail: 50,
    },
    description: "Retry Xero bank payment recording for Stripe captures",
  },
  [RETRY_XERO_INVOICE_CREATION_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: "retry-xero-invoice-creation",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 60_000 },
      removeOnComplete: 50,
      removeOnFail: 50,
    },
    description: "Backfill missing Xero ACCREC invoices",
  },
  [RETRY_REFUND_RECONCILES_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "high",
    pauseOrder: null,
    heartbeatKey: "retry-refund-reconciles",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 60_000 },
      removeOnComplete: 50,
      removeOnFail: 50,
    },
    description: "Replay admin refund DB reconciles",
  },
  [REFRESH_XERO_TOKENS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: "refresh-xero-tokens",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 120_000 },
      removeOnComplete: 20,
      removeOnFail: 20,
    },
    description: "Proactive Xero OAuth token refresh",
  },
  [ENSURE_LOT_INVOICES_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "high",
    pauseOrder: null,
    heartbeatKey: "ensure-lot-invoices",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 60_000 },
      removeOnComplete: 50,
      removeOnFail: 50,
    },
    description: "Reconciliation sweep for sold lots missing payments",
  },
  [CLEANUP_DISPLAY_PAIRINGS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: "cleanup-display-pairings",
    dlq: false,
    showInUi: false,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 60_000 },
      removeOnComplete: 20,
      removeOnFail: 20,
    },
    description: "Expire stale saleroom display pairings",
  },
} as const satisfies Record<string, QueueDefinition>;
