import {
  GC_PENDING_UPLOADS_QUEUE_NAME,
  IMAGE_CLEANUP_QUEUE_NAME,
  IMPERSONATION_SWEEPER_QUEUE_NAME,
  PURGE_EXPIRED_VERIFICATIONS_QUEUE_NAME,
  PURGE_QR_CODE_SCANS_QUEUE_NAME,
  PURGE_SOFT_DELETED_USERS_QUEUE_NAME,
} from "../queue-names.js";
import type { QueueDefinition } from "../types.js";

export const MAINTENANCE_QUEUE_REGISTRY = {
  [IMAGE_CLEANUP_QUEUE_NAME]: {
    producers: ["api"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: "image-cleanup",
    dlq: false,
    showInUi: true,
    allowUiRetries: true,
    repeatable: false,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 200,
      removeOnFail: 500,
    },
    description: "Orphan object deletion",
  },
  [PURGE_QR_CODE_SCANS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: null,
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 5,
      removeOnFail: 50,
    },
    description: "Daily purge for raw QR scan analytics",
  },
  [GC_PENDING_UPLOADS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: "gc-pending-uploads",
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 10,
      removeOnFail: 50,
    },
    description: "Hourly GC for pending uploads",
  },
  [IMPERSONATION_SWEEPER_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: 4,
    heartbeatKey: "impersonation-sweeper",
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 10,
      removeOnFail: 50,
    },
    description: "Sweep stale impersonation sessions",
  },
  [PURGE_EXPIRED_VERIFICATIONS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: "purge-expired-verifications",
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 10,
      removeOnFail: 50,
    },
    description: "Purge expired KYC verifications",
  },
  [PURGE_SOFT_DELETED_USERS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: null,
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 10,
      removeOnFail: 50,
    },
    description: "Weekly purge of soft-deleted users",
  },
} as const satisfies Record<string, QueueDefinition>;
