import {
  MARKETING_EVENTS_CAPI_BATCH_QUEUE_NAME,
  MARKETING_EVENTS_QUEUE_NAME,
  MARKETING_OUTBOX_POLLER_QUEUE_NAME,
  MARKETING_SYNC_QUEUE_NAME,
  PURGE_MARKETING_CLICK_IDS_QUEUE_NAME,
} from "../queue-names.js";
import type { QueueDefinition, QueueRuntimeEnv } from "../types.js";

const marketingEnabled = (env: QueueRuntimeEnv) => env.marketingEventsEnabled;

export const MARKETING_QUEUE_REGISTRY = {
  [MARKETING_SYNC_QUEUE_NAME]: {
    producers: ["api"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: "marketing-sync",
    dlq: false,
    showInUi: true,
    allowUiRetries: true,
    repeatable: false,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 200,
      removeOnFail: 500,
    },
    description: "Newsletter signup → Zoho Campaigns",
  },
  [MARKETING_EVENTS_QUEUE_NAME]: {
    producers: ["api"],
    consumer: "worker",
    criticality: "high",
    pauseOrder: null,
    heartbeatKey: "marketing-events",
    dlq: true,
    showInUi: true,
    allowUiRetries: false,
    repeatable: false,
    enabledWhen: marketingEnabled,
    defaultJobOptions: {
      attempts: 10,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 1000,
      removeOnFail: 5000,
    },
    description: "Marketing event publish (sGTM + Meta CAPI)",
  },
  [MARKETING_EVENTS_CAPI_BATCH_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: null,
    dlq: false,
    showInUi: true,
    allowUiRetries: true,
    repeatable: false,
    enabledWhen: marketingEnabled,
    defaultJobOptions: {
      attempts: 10,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 1000,
      removeOnFail: 5000,
    },
    description: "Meta CAPI batch collector",
  },
  [MARKETING_OUTBOX_POLLER_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "normal",
    pauseOrder: null,
    heartbeatKey: null,
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    enabledWhen: marketingEnabled,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 10,
      removeOnFail: 100,
    },
    description: "Re-enqueue stuck marketing outbox rows",
  },
  [PURGE_MARKETING_CLICK_IDS_QUEUE_NAME]: {
    producers: ["worker"],
    consumer: "worker",
    criticality: "background",
    pauseOrder: null,
    heartbeatKey: null,
    dlq: false,
    showInUi: true,
    allowUiRetries: false,
    repeatable: true,
    enabledWhen: marketingEnabled,
    defaultJobOptions: {
      attempts: 3,
      backoff: { type: "exponential", delay: 5000 },
      removeOnComplete: 5,
      removeOnFail: 50,
    },
    description: "Purge stale marketing click IDs and outbox",
  },
} as const satisfies Record<string, QueueDefinition>;
